apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  labels:
    app: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
      - name: curl-container
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do curl -s http://otel-python-demo-svc.demo.svc.cluster.local/rolldice; sleep 5; done"]
        resources:
            limits:
              cpu: 50m
              memory: 64Mi