apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  labels:
    app: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
      - name: locust
        image: locustio/locust:2.32.0
        imagePullPolicy: Always
        args: ["-H http://otel-python-demo-svc.demo.svc.cluster.local", "-f", "/home/locust/locustfile.py", "--headless", "--only-summary", "-u 1", "-r 1"] #locust -f locust_files/my_locust_file.py --headless -u 100 -r 5
        volumeMounts:
          - mountPath: /home/locust
            name: locust-scripts
        resources:
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
      - name: locust-scripts
        configMap:
          name: locust-scripts